name: Notificar cambios en configuración

on:
  push:
    paths:
      - 'readme.md'  # Se activa si cambia cualquier archivo dentro de config/

jobs:
  notify_teams:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificación a Microsoft Teams
        run: |
          curl -H "Content-Type: application/json" -d '{
            "type": "message",
              "text": "<at>NABAHIN Ali</at> ¡Tienes un mensaje!",
              "mentions": [
                {
                  "id": "ali.nabahin@axians.es",
                  "name": "NABAHIN Ali"
                }
              ]
          }' ${{ secrets.TEAMS_WEBHOOK_URL }}
