name: Notificar cambios en configuración

on:
  push:
    paths:
      - 'readme.md'  # Se activa si cambia cualquier archivo dentro de config/

jobs:
  notify_teams:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificación a Microsoft Teams
        run: |
          curl -H "Content-Type: application/json" -d '{
            "type": "message",
            "attachments": [
              {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                  "version": "1.4",
                  "type": "AdaptiveCard",
                  "body": [
                    {
                      "type": "TextBlock",
                      "text": "🚀 ¡Nueva actualización en el repositorio!"
                    },
                    {
                      "type": "TextBlock",
                      "text": "⚠️ <at>NABAHIN Ali</at>, revisen los cambios en `config/`.\n\n🔗 [Ver en GitHub](https://github.com/${{ github.repository }}/commits/${{ github.ref }})",
                      "wrap": true
                    }
                  ],
                  "msteams": {
                    "entities": [
                      {
                        "type": "mention",
                        "text": "<at>NABAHIN Ali</at>",
                        "mentioned": {
                          "id": "ali.nabahin@axians.es",
                          "name": "NABAHIN Ali"
                        }
                      }
                    ]
                  }
                }
              }
            ]
          }' ${{ secrets.TEAMS_WEBHOOK_URL }}
