name: Notify Changes via Email

on:
  push:
    paths:
      - 'ficheros/prueba/**'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Para obtener el historial completo y ver los cambios

    - name: Check for changes
      id: check_changes
      run: |
        CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} 'ficheros/prueba/')
        echo "changed_files=$CHANGED_FILES" >> $GITHUB_ENV

    - name: Send Email Notification
      if: env.changed_files != ''
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USER }}
        password: ${{ secrets.EMAIL_PASS }}
        subject: "Cambios detectados en la carpeta"
        body: |
          Se detectaron cambios en los siguientes archivos:
          ${{ env.changed_files }}
          
          Detalles de los cambios:
          $(git diff ${{ github.event.before }} ${{ github.sha }} 'ficheros/prueba/')
        to: "raul1.gomez@axians.es"
        secure: false
        from: "${{ secrets.EMAIL_USER }}"




