name: Enviar Notificación por Correo con Archivos Modificados

on:
  push:
    paths:
      - 'ficheros/prueba/**'  # Monitorea todos los cambios dentro de la carpeta 'mi_carpeta'

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Comprobar el código
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Asegúrate de tener acceso a todo el historial de commits

    - name: Obtener los archivos modificados
      id: files
      run: |
        # Compara los archivos entre el último commit y el anterior para detectar los cambios
        git diff --name-only HEAD~1 HEAD > modified_files.txt
        # Filtra los archivos modificados que estén dentro de la carpeta 'mi_carpeta'
        CHANGED_FILES=$(grep '^mi_carpeta/' modified_files.txt)
        echo "Archivos modificados en la carpeta 'mi_carpeta': $CHANGED_FILES"
        
        # Si hay archivos modificados, los almacenamos en una variable de entorno
        if [ -z "$CHANGED_FILES" ]; then
          echo "No hay archivos modificados en mi_carpeta"
          exit 0  # Detener la ejecución si no hay archivos modificados
        else
          echo "$CHANGED_FILES" >> $GITHUB_ENV  # Guardar los archivos modificados en una variable de entorno
        fi

    - name: Enviar correo con archivos adjuntos
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com  # O el servidor SMTP que estés utilizando
        server_port: 587
        username: ${{ secrets.EMAIL_USER }}  # Usuario de tu correo
        password: ${{ secrets.EMAIL_PASS }}  # Contraseña de tu correo (usualmente una "App Password")
        from: ${{ secrets.EMAIL_USER }}
        to: 'ali.nabahin@axians.es, raul1.gomez@axians.es'
        subject: '¡Archivos modificados en el repositorio!'
        body: 'Hola, se han modificado los siguientes archivos en el repositorio. Adjunto los archivos modificados.'
        secure: false
        # Adjuntamos todos los archivos modificados dentro de 'mi_carpeta'
        attachments: |
          ${{ github.workspace }}/$CHANGED_FILES
