name: Notificar cambios en configuración

on:
  push:
    paths:
      - 'readme.md'  # Se activa si cambia cualquier archivo dentro de config/

jobs:
  notify_teams:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificación a Microsoft Teams
        run: |
          curl -H "Content-Type: application/json" -d '{
            "title": "⚠️ Cambios en archivos de configuración",
            "text": "Se han modificado archivos en la carpeta `config/`.\nRevisión de cambios: [Ver en GitHub](https://github.com/${{ github.repository }}/commits/${{ github.ref }})"
          }' ${{ secrets.TEAMS_WEBHOOK_URL }}
