name: Enviar Notificación por Correo con Archivos Modificados

on:
  push:
    paths:
      - 'ficheros/prueba/**'  # Monitorea todos los cambios dentro de la carpeta 'ficheros/prueba'

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Comprobar el código
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Asegúrate de tener acceso a todo el historial de commits

    - name: Obtener archivos modificados
      id: files
      run: |
        # Mostrar los archivos modificados en el último commit
        CHANGED_FILES=$(git diff --name-only HEAD)
        echo "Archivos modificados: $CHANGED_FILES"

        # Filtrar los archivos modificados dentro de 'ficheros/prueba'
        CHANGED_FILES_IN_FOLDER=$(echo "$CHANGED_FILES" | grep '^ficheros/prueba/')
        echo "Archivos modificados dentro de ficheros/prueba: $CHANGED_FILES_IN_FOLDER"

        # Si no hay archivos modificados en 'ficheros/prueba', terminamos el trabajo
        if [ -z "$CHANGED_FILES_IN_FOLDER" ]; then
          echo "No hay archivos modificados en ficheros/prueba"
          exit 0
        fi

        # Guardamos los nombres de los archivos modificados en una variable de entorno
        echo "$CHANGED_FILES_IN_FOLDER" >> $GITHUB_ENV

    - name: Enviar correo con nombres de archivos modificados
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com  # Servidor SMTP
        server_port: 587
        username: ${{ secrets.EMAIL_USER }}  # Usuario de tu correo
        password: ${{ secrets.EMAIL_PASS }}  # Contraseña de tu correo (secreto EMAIL_PASS)
        from: ${{ secrets.EMAIL_USER }}
        to: 'raul1.gomez@axians.es'  # Reemplaza con la dirección de correo del destinatario
        subject: '¡Archivos modificados en el repositorio!'
        body: |
          Hola, se han modificado los siguientes archivos en el repositorio:
          ${{ env.CHANGED_FILES_IN_FOLDER }}



