name: Notificar cambios en configuración

on:
  push:
    paths:
      - 'readme.md'  # Se activa si cambia cualquier archivo dentro de config/

jobs:
  notify_teams:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificación a Microsoft Teams
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{
          "type": "message",
          "text": "¡Hola <at>@NABAHIN Ali</at>, se ha hecho un push a la rama principal!",
          "mentions": [
            {
              "id": 1,
              "mentionText": "@NABAHIN Ali",
              "mentioned": {
                "id": "8:ali.nabahin@axians.es",  # El ID del usuario o su correo
                "name": "NABAHIN Ali"
              }
            }
          ]
          }' ${{ secrets.TEAMS_WEBHOOK_URL }}
